const test=require('node:test'),assert=require('node:assert/strict');
const W=require('../geologger/geoflow-workflow');
const services={validate:()=>({errs:[]}),logic:()=>[],score:()=>100};
function fixture(){return {project:{projectNumber:'T',projectName:'Test',clientName:'Demo',siteAddress:'Demo',reportNumber:'R',loggedBy:'A',reviewBy:'B'},scope:{items:[{status:'acc'}],plan:{totals:{bh:1},labs:[]}},boreholes:[{id:'BH1',plannedDepth:5,termDepth:5}],logs:{BH1:{soil:[{from:0,to:5,material:'CLAY'}],rock:[],samples:[]}}};}
function stage(s,id,svc=services){return W.evaluate(s,svc).stages.find(x=>x.id===id);}
test('workflow evaluation is read-only and has no cross-project cache',()=>{const s=fixture(),before=JSON.stringify(s);assert.equal(stage(s,'master').pct,100);assert.equal(stage({},'master').pct,0);assert.equal(JSON.stringify(s),before);});
test('blank geology rows and core runs alone do not complete field logging',()=>{const s=fixture();s.logs.BH1.soil=[{}];s.logs.BH1.rock=[{from:0,to:5,tcr:90}];assert.equal(stage(s,'field').pct,0);});
test('field blockers cannot coexist with 100 percent completion',()=>{const s=fixture();s.boreholes[0].plannedDepth=10;assert.ok(stage(s,'field').blk.length);assert.ok(stage(s,'field').pct<100);});
test('strict planned depths reject numeric prefixes and non-positive values',()=>{for(const n of ['5m',0,-1]){const s=fixture();s.boreholes[0].plannedDepth=n;assert.ok(stage(s,'plan').blk.length);}});
test('fieldwork and laboratory can proceed in parallel after planning',()=>{const s=fixture();s.logs.BH1.soil=[];s.scope.plan.labs=[{test:'CBR',qty:1}];assert.equal(stage(s,'field').status,'action-needed');assert.equal(stage(s,'lab').status,'action-needed');assert.equal(stage(s,'report').status,'waiting');});
test('lab rows ignore empty test arrays and retain individual test flags',()=>{const s=fixture();s.logs.BH1.samples=[{sid:'A',tests:[]},{sid:'B',tests:' ',mc:true},{sid:'C',tests:['CBR']}];const rows=W.labRows(s);assert.deepEqual(rows.map(r=>r.key),['smp-B','smp-C']);assert.equal(rows[0].tests,'Moisture content');s.labStatus={'smp-B':'Returned','smp-C':'Returned'};assert.equal(stage(s,'lab').pct,100);});
test('missing validation services and non-finite completeness stay blocked',()=>{assert.ok(stage(fixture(),'qa',{}).blk.length);assert.ok(stage(fixture(),'qa',{...services,score:()=>NaN}).blk.length);});
test('a share link does not count as a reviewed report',()=>{const s=fixture();s.share={key:true};assert.equal(stage(s,'issue').pct,0);});
test('handover requires saved current source and approval of the same revision',()=>{const s=fixture();s.reportMeta={BH1:{revision:'P01',generatedDate:'2026-09-05T01:00:00Z',sourceKey:W.sourceKey(s,'BH1')}};s.reportApprovals={BH1:{revision:'P01',at:'2026-09-05T02:00:00Z'}};assert.equal(W.evaluate(s,services).complete,true);s.logs.BH1.soil[0].material='SAND';assert.ok(stage(s,'issue').blk.length);});
test('regenerating a saved report requires a new approval',()=>{const s=fixture();s.reportMeta={BH1:{revision:'P01',generatedDate:'2026-09-05T03:00:00Z',sourceKey:W.sourceKey(s,'BH1')}};s.reportApprovals={BH1:{revision:'P01',at:'2026-09-05T02:00:00Z'}};assert.ok(stage(s,'issue').blk.length);});
